### PR TITLE
hc/63-addLandingPageAndPrimaryCategories

### PR DESCRIPTION
**Pull request by xHayden**
## PR Add Landing Page + Primary Categories Page

Issue Number(s): #63 #64 

What does this PR change and why?

Adds a landing page that has 3 building types that are clickable and take you to another new page that has the primary categories associated with that building type. 

Clicking one of those primary categories should take you to a library page with only the cards relevant to that category.
URL navigation is dynamic and restructured to `/library/buildingType/primaryCategory`.

Card schema is updated to have buildingType and primaryCategory properties of type `string`.

### Checklist

- [x] Created a schema called BuildingType with the following properties:
        - Name
        - Array of PrimaryCategories
- [x] Created a schema called PrimaryCategory with the following properties:
        - Name
        - Array of Cards
 - [x] Created buildingType and primaryCategories field on Card schema
 - [x] In each of those Building Types, created an array of eight PrimaryCategories:
        - Site Planning (SP)
        - Resource Efficiency (RE)
        - Durability and Moisture Management (DU)
        - High-Performance Building Envelope (BE)
        - Energy Efficient HVAC Systems (ES)
        - Indoor Air Quality (IAQ)
        - Plumbing and Irrigation (PI)
        - Efficient Lighting and Appliances (LA)
        - Education and Operations (EO)
  - [x] Displays accurate cards for each building type + primary categories (see other notes)

### Initial Landing Page (/)
- [x] Three building types (multifamily, singleFamily, commercial) displayed + respective logos
- [x] Created a general building type card component which is used to render the three categories
- [x] Landing page is shown in the root URL (/)
- [x] OnClick of a building type redirects to the primary categoires page

### Primary Categories Page (/categories)
- [x] Nine primary categories displayed 
        - Site Planning (SP)
        - Resource Efficiency (RE)
        - Durability and Moisture Management (DU)
        - High Performance Building Envelope (BE)
        - Energy Efficient HVAC Systems (ES)
        - Indoor Air Quality (IAQ)
        - Plumbing and Irrigation (PI)
        - Efficient Lighting and Appliances (LA)
        - Education and Operations (EO)
 - [x] General primary category component created to render the eight  primary categories
 - [x] Primary category page is shown in the /categories URL
 - [x] OnClick of a primary category redirects to the library page
 - [x] Bread crumbs follow figma logic

### How to Test
- Navigate to `/library`
- Click on a building type
- Check that it moves to `/library/buildingType` with the right categories ascribed to that building type
- Click on a category
- Check that it moves to `/library/buildingType/categoryInitials` with the right cards ascribed to that category
- Check that breadcrumbs lead to the right destinations and show up with the right values.

## Other notes
I edited the next.config.js to remove the automatic redirect from `/`, but it had weird caching issues and took a lot of cache clearing and rebuilding to fix. If it won't let you go to the page, try clearing the cache and rebuilding the prod version.
Sometimes there are also problems with loading the /library URL since it used to be something else. 

Constants file created for storing conversion between initials and category names as well as the internal names of buildingTypes versus the displayed names. Any modification of these will have to be done in the Card model as well.

Using getInitialProps instead of getServerSideProps because it allows for more raw request content.

@tawsifkamal should primaryCategories be an array on the Card schema instead of a string so you can have multiple categories for a single card? Same question for buildingType.

### CODE REVIEW

**Comment by nmhossain02** [comment]
Okay, I just talked with @tawsifkamal about this and I can answer your question about which cards to show for which categories. The idea is for each card to have a property of category and building type. I think the previous plan was for each card to reference a document from the Categories and BuildingTypes collections, but it might be easier to just use a string instead. 

This is my suggestion: add the property `category` and `buildingType` to the card schema (both of type `String`). Use [enum validators](https://masteringjs.io/tutorials/mongoose/enum) to limit their possible values. You could then get to making the library view filter based on which category was selected. Personally, I think dynamic URL would be the best way, but this is your call.

**Comment by tawsifkamal** [comment]
> 

Yeah Nabeel's approach makes more sense than having a schema for BuildingType and PrimaryCategory. Most likely there won't be changes/additions so the three building types and 9 categories will be hardcoded values. So you can actually scratch building out the schemas for building type and category and have each card reference one of the building types and categories. that was my bad.

**Comment by tawsifkamal** [comment]
> > 
> 
> Yeah Nabeel's approach makes more sense than having a schema for BuildingType and PrimaryCategory. Most likely there won't be changes/additions so the three building types and 9 categories will be hardcoded values. So you can actually scratch building out the schemas for building type and category and have each card reference one of the building types and categories. that was my bad.

You can take out your `createDefaultBuildingTypes` function and then after this sprint I'll work on setting up the postman with pre-populated data when the categoryType and BuildType properties are added to the card schema.

**Comment by xHayden** [comment]
For some reason, the deploy previous images don't load. Must be a caching thing because their URLs are right. Also, I removed the library URL and set the old library page to be a child of the primaryCategory selector page. Category-specific cards aren't loaded yet (because those cards don't have the category data they need yet).

**Comment by xHayden** [comment]
Blocking bug right now, getServerSideProps was used, but now that getInitialProps is used the database code runs on the client and crashes the page. Somehow, refreshing the page seems to fix that problem, so right now I'm trying to figure out why it gets around it.

**Comment by nmhossain02** [comment]
Weird mongodb error aside, it _looks_ like it's working fine. I'll be looking into this later today

**Comment by nmhossain02** [comment]
I looked into the issue a little bit and think it had to do with `getInitialProps` running both client and server-side. I referred to [this](https://stackoverflow.com/questions/49415755/next-js-fetching-data-in-getinitialprops-server-side-vs-client-side) to try to fix it. In order for a total fix, we'd need an equivalent frontend action for `getCardsPagination()`, but currently it uses `getCards()` instead. This seems to not error out, so I think it's a step in the right direction if nothing else

**Comment by nmhossain02** [comment]
Also, btw, top level index page gives a 404. Might not be important after being merged, but I'll mention it just in case

**Review by tawsifkamal — APPROVED** [review]

**Pull request merged**
